# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true

    working_directory: ~/spring-boot-jib-workbench

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
    - checkout

    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-

    - run: ./gradlew dependencies

    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run: ./gradlew --console=plain test

    - store_test_results:
        path: build/test-results

    - run: ./gradlew --console=plain -x test build

    - run: ./gradlew --console=plain -x test jib
